### ISSUE TITLE
Do you have  a plan to upstream the rk3399-khadas-edgev

### ISSUE THREAD

**Issue by andyshrk** [khadas/linux#12]
Do you have a plan to send the dts support of the rk3399 edgev board to kernel mainline?

**Comment by numbqq** [comment]
Yes, we will try to do it.

**Comment by numbqq** [comment]
Already merged to Rockchip branch, will merge to mainline in 5.3 : https://git.kernel.org/pub/scm/linux/kernel/git/mmind/linux-rockchip.git/commit/?h=v5.3-armsoc/dts64&id=c2aacceedc86af87428d998e23a1aca24fd8aa2e

Close this issue.
