### ISSUE TITLE
no space left

### ISSUE THREAD

**Issue by dreamflyforever** [khadas/linux#38]
Hello,  sir
I use two camera in the VIM3 board, when I open the second camera, occured error "no space left",  i dont know why that,
Thank you if any help.

**Comment by numbqq** [comment]
Hello,

Waht cameras? What's the system? Android or Ubuntu?

**Comment by dreamflyforever** [comment]
Any nomal cameral,  linux system.

**Comment by dreamflyforever** [comment]
Any nomal cameral,  linux system.

**Comment by numbqq** [comment]
Please provide more details.

* which image
* kernel log
* error log
